import { oberknechtAPI } from "oberknecht-api";
import { streamOnlineMessage } from "../parser/notifications/stream.online";
import { oberknechtEmitter } from "oberknecht-emitters";
import { eventsubClientOptions } from "../types/eventsub.client.options";
import { subscriptionType } from "../types/subscription.type";
declare const onStreamOnlineCallback: (notification: streamOnlineMessage) => void;
declare const onErrorCallback: (e: Error) => void;
export declare class oberknechtEventsub {
    #private;
    get symbol(): string;
    get clientData(): any;
    get clientWebsockets(): any;
    get clientWebsocketData(): any;
    get _options(): any;
    get WebSockets(): any;
    OberknechtEmitter: oberknechtEmitter;
    OberknechtAPI: oberknechtAPI;
    constructor(options: eventsubClientOptions);
    connect(): Promise<void>;
    on: (eventName: string | string[], callback: Function) => void;
    once: (eventName: string | string[], callback: Function) => void;
    onError: (callback: typeof onErrorCallback) => void;
    closeWebsocket: (wsNum: number) => any;
    closeWebsockets: () => void;
    onStreamOnline(callback: typeof onStreamOnlineCallback): Promise<void>;
    subscribe(type: subscriptionType, condition: any): Promise<import("oberknecht-api/lib-js/types/endpoints/eventsub").getEventsubSubscriptionsResponse>;
    unsubscribe(id: string): Promise<void>;
    unsubscribeAll(): Promise<void>;
    getSubscriptions(cacheOnly?: boolean, wsNum?: null): Promise<import("oberknecht-api/lib-js/types/endpoints/eventsub").getEventsubSubscriptionsResponse>;
    subscribeToStreamOnline(broadcasters: string | string[]): Promise<unknown>;
}
export {};
